contentColumnType: text
fieldGroup: 3112c2c6-232b-4041-bdd3-f4c1a50e0d95
handle: formLastName
instructions: ''
name: 'Form Last Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
