contentColumnType: string
fieldGroup: 703ee9a3-730f-46bb-b6a5-15afbd712c99
handle: navLinks
instructions: ''
name: 'Nav Links'
searchable: false
settings:
  contentTable: '{{%stc_navlinks}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: 'Add a link'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
